---
version: 2.1
jobs:
  test:
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.3.1
    working_directory: ~/cli-plugin
    steps:
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  test:
    jobs:
      - test
